### ISSUE TITLE
Issues during Demo 1

### ISSUE THREAD

**Issue by Mohammad-khataeii** [Zurehma/SE2-Kiruna_eXplorer#1]
1- In the current Demo version, for Linking a document to more than one, the process was confusing in the way of selecting one, submitting, and a new form opens to do the new link, my suggestion was adding the multiple choosing functionality to link document to each other at the very first phase of creating the new document.

**Comment by Gianluca280600** [comment]
I have modified the form to give the user the possibility to link one or more documents at the same time, replacing the select field with a multi-selection.
