### ISSUE TITLE
Improve Visual Consistency of Map Implementations

### ISSUE THREAD

**Issue by GiancarloVirga** [Zurehma/SE2-Kiruna_eXplorer#2]
In the current demo version the map used to show document and the one used in the creation phase has different styles, giving the user a sense of discontinuity / disharmony during navigation. My suggestion is to use same theme for the map.

**Comment by stefffffffffano** [comment]
Thank you for the suggestion and for having noticed it! I fixed it by using the same style in the two maps (the same TyleLayer).
