### ISSUE TITLE
Sprint 3 issue - unclear pages field 

### ISSUE THREAD

**Issue by AliceSantoro** [Zurehma/SE2-Kiruna_eXplorer#4]
Good morning, 
I am Alice Santoro speaking as a urban planner. 

First of all I want to say that I really liked the way you made error prevention easy  when creating a new document: showing borders constraints  of Kiruna municipality is really helpful!

Considering documents preview, I didn't found the meaning of "pages" and "number of pages" fields clear.  I suggest you to highlight the difference between, according to the given specifications. 

I thank you for the attention, 
Alice Santoro

**Comment by stefffffffffano** [comment]
Good morning, Alice.

First of all, thank you for your kind feedback; it has been greatly appreciated. We have changed the way pages are handled in the card, form, and database to be compliant with what the stakeholder explained to us last time. Thank you once again.
